### ISSUE TITLE
Compile fails.

### ISSUE THREAD

**Issue by JooJooBee666** [PocketSprite/8bkc-nofrendo#2]
Error is:
```
PocketSprite/8bkc-nofrendo/main/./main.c:78:9: error: too few arguments to function 'kcugui_filechooser'
  rom_fd=kcugui_filechooser("*.nes,*.bin", "Select ROM", fccallback, NULL);
```

Looking at the function definition you can see why:
`int kcugui_filechooser(char *glob, char *desc, kcugui_filechooser_cb_t cb, void *usrptr, int flags);`

I hardcoded a 0 in as the fifth parameter in main.c to satiate the compiler.

**Comment by ishotjr** [comment]
@Spritetm @JooJooBee666 FYI I was able to clone and make no problem without modifications (and am currently squinting at *Mega Man 2* - this is fantastic! :bowtie: 🔎 🎮 )! 🚀

**Comment by EggoMyLego** [comment]
I would love to have this emulator, however, since I am so new to linux, I am having trouble installing the necessary programs.
Is there any chance you could attach an already compiled app file?

**Comment by ishotjr** [comment]
@EggoMyLego I can send you the binary if you like? :bowtie:

**Comment by EggoMyLego** [comment]
Yeah, that would be awesome.

**Comment by Spritetm** [comment]
FWIW, there's a compiled version of this available in https://www.reddit.com/r/PocketSprite/comments/8uk80a/testers_wanted_beta_apps/?utm_content=title&utm_medium=hot&utm_source=reddit&utm_name=PocketSprite . In general, the PocketSprite will have posts for any beta releases.

**Comment by ishotjr** [comment]
@Spritetm wow, didn't know there was a subreddit - awesome! :bowtie: 👍

**Comment by JooJooBee666** [comment]
Just tried this again.  My problem turned out to be me failing to do a `git pull --recurse-submodules` when updating the SDK.  All good now.

**Comment by Spritetm** [comment]
Closing this as it seems to have been fixed.
