### ISSUE TITLE
while playing tetris it seems like select is being pressed randomly

### ISSUE THREAD

**Issue by ghost** [PocketSprite/8bkc-nofrendo#4]
at random intervals the preview for the next piece turns off. so i have to press select to get it back. happens very frequently and is very annoying.

**Comment by Spritetm** [comment]
That's more of a support question... but did you update to the latest firmware? That should fix it. https://pocketsprite.com/blogs/news/new-software-update-july-2018

**Comment by ghost** [comment]
Thanks a lot. I've misplaced the device but will double check when I find it again.
